refactor(cli): minor refactor to helper functions and upgrade structopt 0.3.5
dan-da/safe-api pull request #1
Opened 2019-12-17 13:12 UTC by bochaco

@dan-da this PR upgrades structopt, and I was also playing around with the parser but I couldn't get further than where you got to. So I did a minor refactor in the helper functions to read from stdin. I think we can keep this as is for now and see how we can keep evolving it once we try to implement more of reading args from stdin in other commands. 

One thing I noticed is that structopt shows a weird help message in terms of the arguments, it seems the `requires_if` causes that, see the ` <target> [target]` below:
```
$ safe files add -h
safe-files-add 0.6.0
Add a file to an existing FilesContainer on the network

USAGE:
    safe files add [FLAGS] [OPTIONS] <location> <target> [target]
...
```

2020-01-07 17:45 UTC, dan-da requested changes
Looks good overall, just maybe we should not use from_utf8_lossy().   what do you think?

2020-01-07 17:45 UTC, dan-da commented on safe-cli/subcommands/helpers.rs
> +            Ok(String::from_utf8_lossy(&val).to_string())
I worry about using from_utf8_lossy(), as it silently alters the user's input if any non utf8 chars encountered.  User may be using a locale other than UTF-8, or paste in a URL with invalid chars obtained from elsewhere.    I would think its better to use the non lossy version and throw an error.

2020-01-07 17:45 UTC, dan-da commented on safe-cli/subcommands/helpers.rs
> +            Ok(String::from_utf8_lossy(&val).to_string())
here also

2020-01-08 13:49 UTC, bochaco commented
Agreed @dan-da , I just pushed a commit to fix that.

2020-01-08 18:00 UTC, merged